# Generated by Django 2.1 on 2018-09-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180903_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='aboutme',
            field=models.TextField(blank=True, null=True, verbose_name='Обо мне'),
        ),
    ]
