# Generated by Django 2.1 on 2018-09-04 11:12

import core.utils
from django.db import migrations, models
import django_countries.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180903_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='aboutme',
            new_name='info',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_photo',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=core.utils.profile_photo_upload_to, verbose_name='Фото профиля'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Страна'),
        ),
    ]
