# Generated by Django 2.1 on 2018-09-09 09:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180904_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 9, 9, 3, 58, 61177, tzinfo=utc), verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='О себе'),
        ),
    ]
