# Generated by Django 2.1 on 2018-09-09 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180909_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации'),
        ),
    ]
