# Generated by Django 2.1 on 2018-09-09 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180909_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='registration_date',
        ),
    ]
