# Generated by Django 2.1 on 2018-09-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180913_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='csv_file',
            field=models.FileField(blank=True, default='', max_length=128, upload_to='', verbose_name='Сгенерированный CSV'),
        ),
        migrations.AlterField(
            model_name='log',
            name='kml_file',
            field=models.FileField(blank=True, default='', max_length=128, upload_to='', verbose_name='Cгенерированный KML'),
        ),
    ]
