# Generated by Django 2.1 on 2018-09-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180913_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'verbose_name': 'Полетный лог', 'verbose_name_plural': 'Полетные логи'},
        ),
        migrations.AddField(
            model_name='log',
            name='log_directory',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Путь к каталогу лога'),
        ),
    ]
