# Generated by Django 2.1 on 2018-09-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180913_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Краткое описание'),
        ),
    ]
