# Generated by Django 2.1 on 2018-09-19 11:14
# edit on 2018-09-19 11:16 (added HStoreExtension())

import django.contrib.postgres.fields.hstore
from django.db import migrations
from django.contrib.postgres.operations import HStoreExtension


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_log_description'),
    ]

    operations = [
        HStoreExtension(),
        migrations.AddField(
            model_name='log',
            name='data',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
    ]



