# Generated by Django 2.1 on 2018-09-19 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_log_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='description',
        ),
    ]
