# Generated by Django 2.1 on 2018-10-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20180920_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='gpx_file',
            field=models.FileField(blank=True, default='', max_length=256, upload_to='', verbose_name='Cгенерированный GPX'),
        ),
    ]
